# Generated by Django 2.1.2 on 2018-12-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscribe', '0002_auto_20181127_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribing_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
