# Generated by Django 2.1.2 on 2018-12-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscribe', '0003_auto_20181210_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribing_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
