# Generated by Django 2.1.2 on 2018-10-30 07:13

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(help_text='이벤트 제목', max_length=100)),
                ('category', models.CharField(help_text='이벤트 타입(사내/외로 구분)', max_length=50)),
                ('start_at', models.DateTimeField(help_text='이벤트 시작 시점')),
                ('end_at', models.DateTimeField(help_text='이벤트 종료 시점')),
                ('description', models.CharField(blank=True, help_text='이벤트에 대한 상세내용', max_length=300, null=True)),
                ('author', models.CharField(help_text='작성자', max_length=50)),
                ('deleted', models.DateTimeField(help_text='삭제된 시간', null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
