# Generated by Django 2.1.2 on 2018-10-31 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20181031_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
