# Generated by Django 2.1.2 on 2018-11-06 09:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20181106_1033'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('date_related_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='deleted',
            field=models.DateTimeField(help_text='삭제된 시간', null=True),
        ),
    ]
