# Generated by Django 2.1.2 on 2018-11-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='캘린더에서 제공하는 날짜')),
                ('temperature', models.FloatField(help_text='해당 날짜+지역의 기온.', null=True)),
                ('weather', models.CharField(help_text='해당 날짜+지역의 날씨상태.', max_length=16, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='예보가 새로 생성된 시간')),
                ('updated', models.DateTimeField(auto_now=True, help_text='예보가 수정된 시간')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='지역 이름', max_length=10, unique=True)),
                ('latitude', models.FloatField(help_text='위도')),
                ('longitude', models.FloatField(help_text='경도')),
                ('observing_station', models.PositiveSmallIntegerField(help_text='지역별 관측소 번호')),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('date', 'region')},
        ),
    ]
