# Generated by Django 2.1.2 on 2018-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_forecast_and_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='weather',
            field=models.TextField(help_text='해당 날짜+지역의 날씨상태.'),
        ),
    ]
